name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install requests

    - name: Test
      run: |
        python -m flask run &
        sleep 5  # Give Flask some time to start
        response=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:5000)
        if [ "$response" -ne 200 ] ; then
          echo "Failed to reach the Flask app. HTTP response code: $response"
          exit 1
        fi

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: PROD

    steps:
    - uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm i -g vercel

    # - name: Deploy to Vercel
    #   run: |
    #     echo 'VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}' >> $GITHUB_ENV
    #     echo 'VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}' >> $GITHUB_ENV
    #     echo 'VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}' >> $GITHUB_ENV
    #     echo $VERCEL_TOKEN
    #     echo $VERCEL_ORG_ID
    #     echo $VERCEL_PROJECT_ID
    #     vercel --token $VERCEL_TOKEN --prod

    - name: Deploy to Vercel
      run: vercel --token $VERCEL_TOKEN --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}